map_divider_node:
  ros__parameters:
    pcd_path: "/home/okty/map_divider_dev_ws/src/map_divider/data/indoor_outdoor_raw.pcd"
    waypoints_path: "/home/okty/map_divider_dev_ws/src/map_divider/data/indoor_outdoor_wp.csv"
    output_pcd_name: "indoor_outdoor"
    waypoint_interpolation_step: 1.0
    sensor_max_range: 50.0
    sensor_min_elev_deg: -30.0
    sensor_max_elev_deg: 30.0
    octomap_resolution: 0.2
    dilation_radius: 0.2
    dedup_leaf_size: 0.1
    map_divide_step: 15.0
